version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/aminesrr/td6/data:/app/data
    networks:
      - my-network

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - my-network

volumes:
  mongo-data:

networks:
  my-network:
    driver: bridge

